version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: otboo-postgres-db
    environment:
      - POSTGRES_USER=otboo-user
      - POSTGRES_PASSWORD=otboo-password
      - POSTGRES_DB=otboo-db
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
