spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: raymond
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: MySuperSecretJwtKeyThatShouldBeLongEnough123
  expiration: 600000 # 10? (??? ??)
  refresh-token-validity-in-ms: 604800000
